# Generated by Django 3.2.3 on 2021-06-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='generic_profile_picture.png', upload_to='profile_pics'),
        ),
    ]
