# Generated by Django 3.2.3 on 2021-05-31 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='dateime',
            new_name='datetime',
        ),
    ]
