# Generated by Django 3.1.6 on 2021-06-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_dateime_tweet_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
